services:
  backend:
    image: notmithil/ocr-backend:latest
    container_name: expenselens-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    image: notmithil/ocr-frontend:latest
    container_name: expenselens-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  ollama:
    image: notmithil/ollama:latest
    container_name: expenselens-ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
  db:
    image: postgres:15-alpine
    container_name: expenselens-db
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
